# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 800
      min-spare: 30

# 日志配置
logging:
  level:
    com.kiwi: debug
    org.springframework: warn

# Spring配置
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  username: canal
  password: canal